### ISSUE TITLE
[RESEARCH] Arbitrary input

### ISSUE THREAD

**Issue by sergeevabc** [itchyny/base58-go#4]
Dear @itchyny,
It seems your encoder is currently not able to process arbitrary input as follows
```
$ type flower.jpg | base58
expecting a number but got "\x1c\x18\xfb\x95\xc3Jt\xbf\xc6\x0f\xe7)J\x04\x1c\x1e[\x83D\x02u\xfe̴k\xccG-\x04\x9e\x1c!\x90\xa3\x9fX\xc8\x02\xae\xd7;\x03\xe3\x0062\xfe\xce\a\xef\x01\r\x98\x0fXV\xc7\x193}g)\xe75\xe5\x0f\x05\xe5\xc0\x06\x9e\xba\xb7(/\x1a\xc1.J\xec\x89\xe6q\xff\x00\xee-P\x1a\xd0\xe0\x0e\x0f\x97\xf1\x8bû\x10\x9f\x98\xa7\xdb\x05x pX\xb9\x94m\xdf\xc6"
```
What do you think about that? Would it be possible?

**Comment by itchyny** [comment]
What output do you expect? base58 is an encoding for number modulo 58.

**Comment by sergeevabc** [comment]
> What output do you expect? 

Same as Base64, but without a few symbols (zero, capital o, capital i, lower case L, plus and slash), I guess.

**Comment by itchyny** [comment]
Firstly understand that base58 is an encoding from an integer, like `echo 12345 | base58` yields `4ER`. So, assuming the input as the binary of a number, it is actually possible to encode. But the option should be explicit, maybe `--binary, -b` option.

**Comment by sergeevabc** [comment]
This is [flower.jpg][1], unlikely it consists of integers, but any file boils down to 0 and 1 in the end, right?

[1]: https://linx.li/s/flower.jpg

**Comment by itchyny** [comment]
Right. The problem is, `cat /dev/random | base64` is possible because it can encode each 8 bytes but `cat /dev/random | base58` is theoretically impossible, which discourage me from implementing this feature.
